version: '3.8'
services:
  rocketmq-a-s:
    image: apache/rocketmq:4.9.7
    # image: apache/rocketmq:5.1.3
    command: 
    - sh
    - mqbroker
    - -c
    - /home/rocketmq/conf/broker-a-s.conf
    restart: always
    environment:
      JAVA_OPT_EXT: -Xms256m -Xmx521m
    network_mode: host
    # ports:
    # - 10909:10909
    # - 10911:10911
    # - 10912:10912
    volumes:
    - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    - ./rocketmq/conf:/home/rocketmq/conf
    - ./rocketmq/store:/home/rocketmq/store
    - ./rocketmq/logs:/home/rocketmq/logs
